### PR TITLE
upversioning to 1.0.0

### PR DESCRIPTION
**Pull request by vesper2000**
# major

### CODE REVIEW

**Comment by sglanzer-fire** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-link/pull-request/9/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-link)

**Comment by sglanzer-fire** [comment]
Needs a pull/merge from master

**Comment by vesper2000** [comment]
merged and successfully built

**Comment by sglanzer-fire** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-link/pull-request/9/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-link)

**Pull request merged**
